### ISSUE TITLE
ERROR: Parser error: syntax error in file ub.scad, line 331 when running the DEMO.scad project

### ISSUE THREAD

**Issue by jmbjr** [UBaer21/UB.scad#2]
reproduction steps:

0) install latest version of openSCAD (2021.01). windows x64 exe installer version.
1) clone UB.scad github repo (version 9c519ba)
2) copy ub.scad to Documents/openscad/libraries
3) open DEMO.scad 

expected results:
DEMO.scad should open with no errors.

observed results:
![image](https://user-images.githubusercontent.com/3990931/141655666-210be3bf-db58-41ad-a075-2d68a9af0689.png)
ERROR: Parser error: syntax error in file ub.scad, line 331

what I've tried:
the error on line 331 is highlighting this section:
`if (!help&&!anima) if(version()[0]<2021)echo    ("<h4 style=background-color:lightgrey>••••• Help off       use: helpsw=1;  •••••");
    else echo    ("❌••••• Help off       use: helpsw=1;  •••••");` and is specifically highlighting the 3rd dot in the echo statement in the else.  i.e. "X . . [.] . . Help off..."   it's the [.] that is highlighted.

I tried to change the string that's being echoed, but that did not affect it. it still complained.

I tried removing the  conditional and it just errors out in a different conditional upstream.

because I'm not familiar with UB.scad yet, I didn't try anything else and decided to submit an issue to see if this is a known issue or if perhaps I need to use a specific build of openSCAD rather than the latest 2021.01 that I found on the website.

**Comment by UBaer21** [comment]
thx -a colon was redundant, which was ignored by snapshot 21.10.19
