### ISSUE TITLE
Error parsing function star

### ISSUE THREAD

**Issue by kvikindi** [UBaer21/UB.scad#5]
Version: 22.038
OpenSCAD: 2021.01
Windows 10

When opening, or trying to import ub.scad, I keep getting the same error, `ERROR: Parser error: syntax error in file ub.scad, line 578`.

This is within the function _star_, and when I simply remove that whole section (line 569 to 581), the whole file seems to "compile" correctly.

For whatever reason, OpenSCAD highlights the "r" in `winkel2=((radial?[1,1]*angle...`, line 577, but I am nowhere close to finding a solution to it.

Hopefully this is simply down to my system, and not others'.

**Comment by kvikindi** [comment]
Upgraded to OpenSCAD dev 2022.02.04, and everything is perfect.
Problem existed between keyboard and chair.

**Comment by UBaer21** [comment]
also fixed by the ub.scad  version β22|042  ( the release β22|022 should
also be fine)
was caused by an redundant colon (which newer SCAD ignore but causing error
in 2021.01 )
however there are a lot of bugfixes and new features in the dev versions.

anyway Thanks for reporting this!
